### PR TITLE
Add ms graph

### PR DESCRIPTION
**Pull request by melvinfolkers**

### CODE REVIEW

**Comment by melvinfolkers** [comment]
In This PR
===

- Changed mailing from smtplib to using ms graph api. 
- Old environment variables needed to send e-mail:  EMAIL_USER, EMAIL_PW
- New environment variables needed to send e-mail: EMAIL_USER, MAIL_TENANT_ID, MAIL_CLIENT_ID, MAIL_CLIENT_SECRET

**Comment by TimvdHeijden** [comment]
@melvinfolkers @erfannariman What still needs to happen before this can be released?

**Comment by TimvdHeijden** [comment]
@erfannariman @melvinfolkers The send_mail function now returns the response, so the user can use it according her/his use case. Also the tests now assert the status_code instead of just running the function.

**Review by erfannariman — APPROVED** [review]
Looks good @TimvdHeijden

**Pull request merged**
